(function () {
  const teacherA = {
    id: "user-lena",
    name: "Lena Morales",
    email: "lena.morales@stanbridge.example",
    passwordHash: "mock:c3RhbmJyaWRnZTIwMjY=",
    role: "Teacher",
    createdAt: "2026-06-15T09:00:00.000Z",
  };

  const teacherB = {
    id: "user-eli",
    name: "Eli Harper",
    email: "eli.harper@stanbridge.example",
    passwordHash: "mock:c3RhbmJyaWRnZTIwMjY=",
    role: "Teacher",
    createdAt: "2026-06-17T10:00:00.000Z",
  };

  const admin = {
    id: "user-admin",
    name: "Maren Sato",
    email: "maren.sato@stanbridge.example",
    passwordHash: "mock:c3RhbmJyaWRnZTIwMjY=",
    role: "Administrator",
    createdAt: "2026-06-01T08:00:00.000Z",
  };

  const students = [
    {
      id: "stu-ava-brooks",
      firstName: "Ava",
      lastName: "Brooks",
      grade: "K",
      email: "ava.brooks@student.stanbridge.example",
      photoUrl: "",
      supportSummary: "Benefits from visual routines, gentle transition warnings, and movement before seated work.",
      supportNeeds: ["Sensory", "Transition Planning", "Speech/Language"],
      strengths: ["Warm peer connection", "Pattern recognition", "Music memory"],
      motivators: ["Songs", "Sticker choices", "Helper jobs"],
      sensoryNeeds: ["Movement before circle", "Reduced noise during arrival"],
      triggers: ["Unexpected schedule changes", "Crowded line-up"],
      communicationStyle: "Uses short verbal phrases, gestures, and picture choices. Responds well to wait time.",
      accommodations: ["Picture schedule", "First-then board", "Noise-reducing headphones"],
      currentGoals: ["Ask for help using a phrase or card", "Transition with one prompt"],
      parentContacts: [
        { name: "Morgan Brooks", email: "morgan.brooks@example.com", phone: "(415) 555-0101", relationship: "Guardian" },
      ],
      emergencyContacts: [{ name: "Taylor Brooks", phone: "(415) 555-0131", relationship: "Aunt" }],
      profile: {
        interests: "Music, classroom jobs, sorting games, looking at picture books.",
        preferredActivities: "Choice board, rhythm games, sensory path, paired read-aloud.",
        confidenceBuilders: "Specific praise, familiar routines, being the line helper.",
        successfulMoments: "Ava joined morning meeting with headphones and completed two picture-sort tasks.",
        whatWorkedRecently: "Previewing the transition with a picture card and a two-minute timer.",
        preferredCommunicationStyle: "Short prompts with visuals and time to respond.",
        helpSigns: "Looks toward teacher and taps the choice card.",
        confusedSigns: "Stops moving materials and scans the room.",
        overwhelmedSigns: "Covers ears, turns away, or sits under table.",
        bestPrompts: "Show first step, offer two choices, and pause.",
        peerNotes: "Enjoys parallel play and responds to peers who use clear invitations.",
        speechLanguageNotes: "Picture-supported expressive language is helpful.",
        conversationStarters: "Ask about the song of the day or classroom helper job.",
        whatNotToDo: "Avoid rapid repeated questions or surprise touch.",
        arrival: "Arrives best with quiet greeting and direct path to cubby.",
        transitionSupport: "Use countdown, picture cue, and helper role.",
        materialsOrganization: "Needs adult check for folder and water bottle.",
        breaksNeeded: "Movement path after arrival and before table work.",
        homeworkSupport: "Family uses a one-step visual routine.",
        seating: "Front corner seat near visual schedule.",
        reminders: "Water reminder after recess.",
        attendanceNotes: "Arrival can be slow after busy mornings.",
        supportChecklist: ["Picture schedule ready", "Headphones available", "Movement path open"],
        efBestSupports: "First-then board, single-step directions, and modeled start.",
        efCurrentGoal: "Begin a familiar table task with one adult prompt.",
        efNextStrategy: "Pair task start with a chosen helper job.",
        sensorySensitivities: "Noise during arrival and lunch transition.",
        sensorySeeking: "Movement, rhythmic tapping, carrying weighted classroom bin.",
        helpfulTools: "Headphones, lap pad, rhythm sticks, choice board.",
        calmingStrategies: "Quiet corner, song choice, deep pressure with cushion.",
        regulationSigns: "Sings quietly, watches teacher model, reaches for schedule.",
        escalationSigns: "Ear covering, hiding, dropped materials.",
        recoveryStrategies: "Reduce language, offer quiet space, re-enter with helper role.",
        environmentalTriggers: "Crowded hallway and loud lunchroom.",
        breakOptions: "Sensory path, quiet corner, breathing card.",
      },
      createdAt: "2026-06-01T08:20:00.000Z",
      updatedAt: "2026-07-08T15:20:00.000Z",
    },
    {
      id: "stu-zoe-alvarez",
      firstName: "Zoe",
      lastName: "Alvarez",
      grade: "3",
      email: "zoe.alvarez@student.stanbridge.example",
      photoUrl: "",
      supportSummary: "Strong visual thinker who does best with predictable routines, explicit social scripts, and reading support.",
      supportNeeds: ["Reading Support", "Anxiety", "Communication"],
      strengths: ["Detailed drawing", "Visual memory", "Kindness with younger students"],
      motivators: ["Sketching", "Animal facts", "Choice of reading spot"],
      sensoryNeeds: ["Low-clutter desk", "Quiet reading area"],
      triggers: ["Timed reading", "Unstructured partner work"],
      communicationStyle: "Thoughtful verbal communicator; may need time to formulate responses.",
      accommodations: ["Audiobook access", "Preview vocabulary", "Social script cards"],
      currentGoals: ["Use decoding strategy before asking for word", "Join partner work with a script"],
      parentContacts: [
        { name: "Isabel Alvarez", email: "isabel.alvarez@example.com", phone: "(415) 555-0102", relationship: "Mother" },
        { name: "Renee Alvarez", email: "renee.alvarez@example.com", phone: "(415) 555-0103", relationship: "Mother" },
      ],
      emergencyContacts: [{ name: "Victor Alvarez", phone: "(415) 555-0132", relationship: "Grandparent" }],
      profile: {
        interests: "Drawing animals, graphic novels, plant science, classroom library jobs.",
        preferredActivities: "Illustrated vocabulary cards, partner drawing warm-ups, audiobook preview.",
        confidenceBuilders: "Private preview before reading aloud and praise for strategy use.",
        successfulMoments: "Zoe explained her science diagram to a peer using prepared sentence starters.",
        whatWorkedRecently: "A vocabulary preview lowered anxiety before whole-group reading.",
        preferredCommunicationStyle: "Warm one-to-one prompts, sentence starters, and time to think.",
        helpSigns: "Raises hand halfway or quietly says 'I'm stuck.'",
        confusedSigns: "Rereads same line, looks down, stops writing.",
        overwhelmedSigns: "Tears, whispered self-criticism, asks to go to the bathroom.",
        bestPrompts: "Ask which strategy she wants to try first and offer a starter phrase.",
        peerNotes: "Responds well to structured roles in partner work.",
        speechLanguageNotes: "Benefits from expressive sentence frames for group discussion.",
        conversationStarters: "Animal facts, sketchbook, science observations.",
        whatNotToDo: "Avoid public correction during reading.",
        arrival: "Settles quickly when morning task is visual.",
        transitionSupport: "Needs preview for partner/group transitions.",
        materialsOrganization: "Checklist taped inside desk helps.",
        breaksNeeded: "Short drawing reset after hard reading block.",
        homeworkSupport: "Audio support and parent signature routine.",
        seating: "Near teacher during literacy, quiet edge during independent reading.",
        reminders: "Water bottle and reading folder check.",
        attendanceNotes: "Tardy on occasional therapy mornings.",
        supportChecklist: ["Audiobook loaded", "Vocabulary cards ready", "Partner role assigned"],
        efBestSupports: "Visual checklist, previewed materials, and clear start line.",
        efCurrentGoal: "Track reading folder and complete two-step literacy routine.",
        efNextStrategy: "Use a small desk card: preview, read, mark, ask.",
        sensorySensitivities: "Visual clutter and noise during group rotations.",
        sensorySeeking: "Doodling can be regulating when bounded.",
        helpfulTools: "Quiet reading tent, sketch card, colored reading strip.",
        calmingStrategies: "Breathing with drawing, quiet walk, teacher check-in.",
        regulationSigns: "Uses reading strip, breathes, asks for starter.",
        escalationSigns: "Tearfulness and avoidance language.",
        recoveryStrategies: "Private reset and return with a lower-risk first item.",
        environmentalTriggers: "Timed tasks and loud centers.",
        breakOptions: "Library shelf job or two-minute sketch.",
      },
      createdAt: "2026-06-01T08:21:00.000Z",
      updatedAt: "2026-07-08T14:30:00.000Z",
    },
    {
      id: "stu-mateo-chen",
      firstName: "Mateo",
      lastName: "Chen",
      grade: "2",
      email: "mateo.chen@student.stanbridge.example",
      photoUrl: "",
      supportSummary: "Curious builder who benefits from clear first steps, reduced auditory load, and frequent movement.",
      supportNeeds: ["Executive Functioning", "Sensory", "Math Strength"],
      strengths: ["Spatial reasoning", "Curiosity", "Mental math"],
      motivators: ["Building materials", "Puzzles", "Choice of marker color"],
      sensoryNeeds: ["Movement breaks", "Headphones during assemblies"],
      triggers: ["Long carpet lessons", "Multi-step directions without visuals"],
      communicationStyle: "Energetic verbal style; responds to concise prompts and visual sequence cards.",
      accommodations: ["Visual checklist", "Movement jobs", "Chunked directions"],
      currentGoals: ["Complete morning routine independently", "Use checklist for multi-step work"],
      parentContacts: [{ name: "Grace Chen", email: "grace.chen@example.com", phone: "(415) 555-0104", relationship: "Mother" }],
      emergencyContacts: [{ name: "Daniel Chen", phone: "(415) 555-0133", relationship: "Father" }],
      profile: {
        interests: "Engineering kits, number games, maps, marble runs.",
        preferredActivities: "Hands-on math, build-to-explain, station jobs.",
        confidenceBuilders: "Let Mateo demonstrate a structure or number strategy.",
        successfulMoments: "Mateo completed a three-step math station after using a visual checklist.",
        whatWorkedRecently: "The first-step card helped him begin writing about his build.",
        preferredCommunicationStyle: "Direct, upbeat language and one instruction at a time.",
        helpSigns: "Makes jokes or leaves seat when unsure.",
        confusedSigns: "Starts a different task or asks unrelated questions.",
        overwhelmedSigns: "Increased volume, rapid movement, refusal language.",
        bestPrompts: "Point to checklist and ask, 'What is step one?'",
        peerNotes: "Can lead build tasks; needs role clarity to share materials.",
        speechLanguageNotes: "Narrating steps supports sequencing.",
        conversationStarters: "Ask what he would build to solve a problem.",
        whatNotToDo: "Avoid long verbal instructions from across the room.",
        arrival: "Benefits from a materials bin job.",
        transitionSupport: "Needs movement before carpet.",
        materialsOrganization: "Color-coded folder system is emerging.",
        breaksNeeded: "Frequent movement jobs improve focus.",
        homeworkSupport: "Short checklist and timer.",
        seating: "Flexible stool near front for direct cueing.",
        reminders: "Snack and water after recess.",
        attendanceNotes: "Consistent attendance.",
        supportChecklist: ["Math manipulatives ready", "Checklist visible", "Movement job assigned"],
        efBestSupports: "Clear first step, timer, visual station list.",
        efCurrentGoal: "Use checklist to complete morning routine.",
        efNextStrategy: "Add self-check box at end of each station.",
        sensorySensitivities: "Assemblies and echoing spaces.",
        sensorySeeking: "Standing, lifting bins, chair push-ups.",
        helpfulTools: "Wobble stool, headphones, heavy-work jobs.",
        calmingStrategies: "Wall pushes, quiet hallway walk, puzzle reset.",
        regulationSigns: "Checks list, lowers voice, asks for job.",
        escalationSigns: "Fast movement and louder voice.",
        recoveryStrategies: "Heavy-work break and a concrete re-entry task.",
        environmentalTriggers: "Long seated instruction.",
        breakOptions: "Delivery job, build reset, hallway loop.",
      },
      createdAt: "2026-06-01T08:22:00.000Z",
      updatedAt: "2026-07-08T13:50:00.000Z",
    },
    {
      id: "stu-nia-patel",
      firstName: "Nia",
      lastName: "Patel",
      grade: "4",
      email: "nia.patel@student.stanbridge.example",
      photoUrl: "",
      supportSummary: "Reflective learner with strong science reasoning; needs anxiety-aware transitions and written task breakdowns.",
      supportNeeds: ["Anxiety", "Executive Functioning", "Writing Support"],
      strengths: ["Science reasoning", "Empathy", "Careful observation"],
      motivators: ["Plant care", "Lab roles", "Private feedback"],
      sensoryNeeds: ["Quiet work start", "Predictable seating"],
      triggers: ["Substitute teachers", "Open-ended writing without model"],
      communicationStyle: "Quiet, precise verbal communication; shares more in small groups.",
      accommodations: ["Written first step", "Model text", "Check-in before transitions"],
      currentGoals: ["Begin writing from a model within five minutes", "Use a coping strategy before asking to leave"],
      parentContacts: [{ name: "Ravi Patel", email: "ravi.patel@example.com", phone: "(415) 555-0105", relationship: "Father" }],
      emergencyContacts: [{ name: "Leena Patel", phone: "(415) 555-0134", relationship: "Aunt" }],
      profile: {
        interests: "Botany, weather, careful note-taking, helping care for class plants.",
        preferredActivities: "Science observations, partner with clear role, quiet drafting station.",
        confidenceBuilders: "Private recognition and visible evidence of growth.",
        successfulMoments: "Nia used the writing model to draft a strong science explanation.",
        whatWorkedRecently: "A two-column planning frame reduced writing start time.",
        preferredCommunicationStyle: "Private check-ins and written choices.",
        helpSigns: "Places pencil down and waits quietly.",
        confusedSigns: "Erases repeatedly or rewrites the date.",
        overwhelmedSigns: "Tears, requests nurse, freezes at desk.",
        bestPrompts: "Validate, point to model, ask for the smallest next step.",
        peerNotes: "Does well with a reliable peer and defined role.",
        speechLanguageNotes: "No current speech/language service notes.",
        conversationStarters: "Plants, weather data, lab jobs.",
        whatNotToDo: "Avoid calling on her unexpectedly during anxiety signs.",
        arrival: "Needs quiet start and predictable morning plan.",
        transitionSupport: "Preview changes, especially with substitutes.",
        materialsOrganization: "Very organized when routine is stable.",
        breaksNeeded: "Short quiet reset before writing can help.",
        homeworkSupport: "Break long writing into planning and drafting.",
        seating: "Consistent side seat near calm peer.",
        reminders: "Check assignment planner before dismissal.",
        attendanceNotes: "Occasional late arrival after difficult mornings.",
        supportChecklist: ["Writing model available", "Transition preview delivered", "Planner checked"],
        efBestSupports: "Model, two-column planner, teacher check before writing.",
        efCurrentGoal: "Initiate written response with planning frame.",
        efNextStrategy: "Use a three-sentence starter bank for open responses.",
        sensorySensitivities: "Sudden noise and crowded substitute transitions.",
        sensorySeeking: "Plant care job can regulate.",
        helpfulTools: "Quiet station, breathing card, planner frame.",
        calmingStrategies: "Plant watering, breathing, brief hallway check-in.",
        regulationSigns: "Looks at model, writes a phrase, asks quietly.",
        escalationSigns: "Freezing, tears, repeated erasing.",
        recoveryStrategies: "Reduce audience, offer written first step, rejoin with defined role.",
        environmentalTriggers: "Unknown adult, unmodeled writing.",
        breakOptions: "Plant care, quiet station, counselor check if needed.",
      },
      createdAt: "2026-06-01T08:23:00.000Z",
      updatedAt: "2026-07-08T16:40:00.000Z",
    },
    {
      id: "stu-lucas-rivera",
      firstName: "Lucas",
      lastName: "Rivera",
      grade: "5",
      email: "lucas.rivera@student.stanbridge.example",
      photoUrl: "",
      supportSummary: "Strong oral storyteller who benefits from writing scaffolds, assignment tracking, and structured peer roles.",
      supportNeeds: ["Writing Support", "Executive Functioning", "Communication"],
      strengths: ["Storytelling", "Humor", "Oral comprehension"],
      motivators: ["Podcast clips", "Choice topics", "Peer leadership"],
      sensoryNeeds: ["Movement during planning", "Low-distraction writing spot"],
      triggers: ["Blank page writing", "Ambiguous group expectations"],
      communicationStyle: "Expressive verbal communicator; benefits from turning oral rehearsal into written steps.",
      accommodations: ["Speech-to-text option", "Graphic organizer", "Group role card"],
      currentGoals: ["Use organizer before drafting", "Record homework in planner"],
      parentContacts: [{ name: "Elena Rivera", email: "elena.rivera@example.com", phone: "(415) 555-0106", relationship: "Mother" }],
      emergencyContacts: [{ name: "Marco Rivera", phone: "(415) 555-0135", relationship: "Uncle" }],
      profile: {
        interests: "Podcasts, sports commentary, graphic novels, comedy sketches.",
        preferredActivities: "Oral rehearsal, storyboard, interview-style writing.",
        confidenceBuilders: "Let him share a strong verbal idea before writing.",
        successfulMoments: "Lucas used speech-to-text to capture a persuasive paragraph.",
        whatWorkedRecently: "A storyboard helped turn his idea into a structured draft.",
        preferredCommunicationStyle: "Conversational prompts and explicit role agreements.",
        helpSigns: "Talks around the task or asks to sharpen pencil.",
        confusedSigns: "Begins with unrelated sentence or abandons planner.",
        overwhelmedSigns: "Jokes, distracts peers, avoids writing.",
        bestPrompts: "Ask him to say the sentence, then write the first five words.",
        peerNotes: "Can be a positive group energy with defined role.",
        speechLanguageNotes: "Oral rehearsal supports written expression.",
        conversationStarters: "Podcast, game recap, funny headline.",
        whatNotToDo: "Avoid interpreting humor as defiance before checking task clarity.",
        arrival: "Needs planner visible on desk.",
        transitionSupport: "Group role reminder before collaborative work.",
        materialsOrganization: "Planner check at dismissal.",
        breaksNeeded: "Short movement before longer writing.",
        homeworkSupport: "Assignment tracking and parent sign-off.",
        seating: "Near focused peer for writing; flexible for discussion.",
        reminders: "Planner and laptop charged.",
        attendanceNotes: "Consistent attendance.",
        supportChecklist: ["Organizer ready", "Speech-to-text available", "Planner check"],
        efBestSupports: "Organizer, oral rehearsal, planner routine.",
        efCurrentGoal: "Track assignments accurately in planner.",
        efNextStrategy: "End-of-class two-minute planner audit.",
        sensorySensitivities: "Busy visual desk can distract.",
        sensorySeeking: "Movement and gesturing while thinking.",
        helpfulTools: "Standing desk, storyboard cards, noise buffer.",
        calmingStrategies: "Walk-and-talk planning, then return to draft.",
        regulationSigns: "Rehearses sentence, writes starter, checks organizer.",
        escalationSigns: "Silly avoidance and peer distraction.",
        recoveryStrategies: "Private prompt and a quick oral restart.",
        environmentalTriggers: "Blank pages and vague group roles.",
        breakOptions: "Water walk or standing planning station.",
      },
      createdAt: "2026-06-01T08:24:00.000Z",
      updatedAt: "2026-07-07T21:10:00.000Z",
    },
    {
      id: "stu-maya-thompson",
      firstName: "Maya",
      lastName: "Thompson",
      grade: "6",
      email: "maya.thompson@student.stanbridge.example",
      photoUrl: "",
      supportSummary: "Insightful reader transitioning to middle school routines; benefits from checklist systems and quiet regulation options.",
      supportNeeds: ["Transition Planning", "Executive Functioning", "Anxiety"],
      strengths: ["Literary insight", "Self-advocacy", "Organization when routine is clear"],
      motivators: ["Book clubs", "Private goal tracking", "Choice seating"],
      sensoryNeeds: ["Quiet lunch option", "Reduced hallway crowding"],
      triggers: ["Locker timing", "Schedule changes", "Noisy hallway"],
      communicationStyle: "Clear self-advocate when given private space to name needs.",
      accommodations: ["Locker checklist", "Transition pass", "Weekly goal conference"],
      currentGoals: ["Use locker checklist independently", "Request transition support before overwhelm"],
      parentContacts: [{ name: "Janelle Thompson", email: "janelle.thompson@example.com", phone: "(415) 555-0107", relationship: "Guardian" }],
      emergencyContacts: [{ name: "Robert Thompson", phone: "(415) 555-0136", relationship: "Grandparent" }],
      profile: {
        interests: "Mystery novels, book clubs, organizing supplies, journaling.",
        preferredActivities: "Literature circles, planner reflection, quiet independent reading.",
        confidenceBuilders: "Goal charts and genuine responsibility.",
        successfulMoments: "Maya used the locker checklist and arrived prepared for science.",
        whatWorkedRecently: "Transition pass reduced stress during noisy hallway period.",
        preferredCommunicationStyle: "Private, respectful conversation with written options.",
        helpSigns: "Emails teacher or waits after class.",
        confusedSigns: "Checks planner repeatedly, becomes quiet.",
        overwhelmedSigns: "Rigid tone, tears, asks to avoid hallway.",
        bestPrompts: "Offer a private two-choice support path.",
        peerNotes: "Thrives in small, purposeful groups.",
        speechLanguageNotes: "Strong language comprehension; no current support note.",
        conversationStarters: "Books, organization systems, school clubs.",
        whatNotToDo: "Avoid public processing of locker difficulties.",
        arrival: "Check planner and first-period materials.",
        transitionSupport: "Allow early hallway pass when needed.",
        materialsOrganization: "Locker checklist is key.",
        breaksNeeded: "Quiet lunch or library pass after loud transitions.",
        homeworkSupport: "Planner review on Thursday.",
        seating: "Quiet edge with view of board.",
        reminders: "Locker reset before lunch.",
        attendanceNotes: "Consistent attendance.",
        supportChecklist: ["Locker checklist", "Transition pass", "Planner conference"],
        efBestSupports: "Planner preview, locker checklist, weekly conference.",
        efCurrentGoal: "Arrive to each class with correct materials.",
        efNextStrategy: "Color-code class folders by schedule block.",
        sensorySensitivities: "Hallway noise and lunch crowding.",
        sensorySeeking: "Organizing can be calming.",
        helpfulTools: "Quiet pass, planner, noise-reducing earbuds in hall when allowed.",
        calmingStrategies: "Library reset, journaling, breathing app.",
        regulationSigns: "Uses planner and names need.",
        escalationSigns: "Tearfulness, rigidity, refusal to enter hallway.",
        recoveryStrategies: "Quiet pass and re-entry with prepared materials.",
        environmentalTriggers: "Locker rush and unexpected schedule changes.",
        breakOptions: "Library pass or quiet lunch table.",
      },
      createdAt: "2026-06-01T08:25:00.000Z",
      updatedAt: "2026-07-08T12:10:00.000Z",
    },
    {
      id: "stu-oliver-kim",
      firstName: "Oliver",
      lastName: "Kim",
      grade: "7",
      email: "oliver.kim@student.stanbridge.example",
      photoUrl: "",
      supportSummary: "Analytical STEM learner who benefits from flexibility support, explicit group norms, and regulation breaks after lunch.",
      supportNeeds: ["Cognitive Flexibility", "Sensory", "Group Work"],
      strengths: ["Coding", "Systems thinking", "Accuracy"],
      motivators: ["Robotics", "Logic puzzles", "Data roles"],
      sensoryNeeds: ["Noise management after lunch", "Predictable lab setup"],
      triggers: ["Unexpected group changes", "Noisy collaborative labs"],
      communicationStyle: "Precise language; may sound blunt when anxious or overloaded.",
      accommodations: ["Structured peer roles", "Noise plan", "Change preview"],
      currentGoals: ["Use flexible response script", "Complete group role before redirecting peers"],
      parentContacts: [{ name: "Hannah Kim", email: "hannah.kim@example.com", phone: "(415) 555-0108", relationship: "Mother" }],
      emergencyContacts: [{ name: "Min Kim", phone: "(415) 555-0137", relationship: "Father" }],
      profile: {
        interests: "Robotics, coding, chess, data visualization.",
        preferredActivities: "Debugging, lab data role, independent proof checks.",
        confidenceBuilders: "Accuracy-based roles and private recognition.",
        successfulMoments: "Oliver completed the data lead role and accepted a peer's alternate method.",
        whatWorkedRecently: "A role card reduced conflict during robotics lab.",
        preferredCommunicationStyle: "Precise, literal language with clear expectations.",
        helpSigns: "Corrects peers repeatedly or asks for rule clarification.",
        confusedSigns: "Insists task is impossible due to unclear rule.",
        overwhelmedSigns: "Sharp tone, withdrawal, refusal to continue group task.",
        bestPrompts: "Acknowledge accuracy, then return to shared goal and role.",
        peerNotes: "Structured roles prevent over-correction.",
        speechLanguageNotes: "Pragmatic communication scripts support group work.",
        conversationStarters: "Robotics challenge, coding bug, chess strategy.",
        whatNotToDo: "Avoid vague social feedback such as 'be nicer' without a concrete replacement.",
        arrival: "Ready with laptop; may need check after schedule changes.",
        transitionSupport: "Preview changes in lab partners.",
        materialsOrganization: "Digital files organized; physical binder needs check.",
        breaksNeeded: "Post-lunch quiet reset helps.",
        homeworkSupport: "Digital assignment tracker.",
        seating: "Near calm peer, away from door noise.",
        reminders: "Binder check and lab role card.",
        attendanceNotes: "Consistent attendance.",
        supportChecklist: ["Role card", "Noise plan", "Change preview"],
        efBestSupports: "Digital tracker, lab role, explicit flexible-thinking script.",
        efCurrentGoal: "Use role card before correcting peer process.",
        efNextStrategy: "Add 'my role / team role' prompt card.",
        sensorySensitivities: "Lunch noise and lab equipment sounds.",
        sensorySeeking: "Keyboard fidget and precise setup.",
        helpfulTools: "Headphones during independent work, role card, quiet lab corner.",
        calmingStrategies: "Quiet reset, chess puzzle, debugging task.",
        regulationSigns: "Uses script and lowers tone.",
        escalationSigns: "Blunt correction, refusal, leaving group table.",
        recoveryStrategies: "Quiet space and return with explicit role.",
        environmentalTriggers: "Noisy group labs after lunch.",
        breakOptions: "Coding puzzle or quiet corner.",
      },
      createdAt: "2026-06-01T08:26:00.000Z",
      updatedAt: "2026-07-08T17:05:00.000Z",
    },
    {
      id: "stu-jordan-lee",
      firstName: "Jordan",
      lastName: "Lee",
      grade: "8",
      email: "jordan.lee@student.stanbridge.example",
      photoUrl: "",
      supportSummary: "Creative writer with strong voice; task initiation improves when the first step is written clearly.",
      supportNeeds: ["Executive Functioning", "Writing Strength", "Anxiety"],
      strengths: ["Creative writing", "Perspective-taking", "Vocabulary"],
      motivators: ["Choice prompts", "Music while drafting", "Peer publishing"],
      sensoryNeeds: ["Calm start after lunch", "Optional headphones"],
      triggers: ["Large open-ended projects", "Group work without role", "Loud lunch transition"],
      communicationStyle: "Thoughtful writer; may communicate more easily in writing than speech when stressed.",
      accommodations: ["Written first step", "Project milestones", "Headphones during drafting"],
      currentGoals: ["Start assignments within five minutes using first-step card", "Track long-term project milestones"],
      parentContacts: [
        { name: "Alex Lee", email: "alex.lee@example.com", phone: "(415) 555-0109", relationship: "Parent" },
        { name: "Sam Lee", email: "sam.lee@example.com", phone: "(415) 555-0110", relationship: "Parent" },
      ],
      emergencyContacts: [{ name: "Kira Lee", phone: "(415) 555-0138", relationship: "Aunt" }],
      profile: {
        interests: "Creative writing, poetry, playlists, character design, graphic novels.",
        preferredActivities: "Choice writing, quiet drafting, peer publishing with consent.",
        confidenceBuilders: "Recognize voice and originality; connect tasks to story craft.",
        successfulMoments: "Jordan drafted a vivid opening paragraph after choosing a first sentence starter.",
        whatWorkedRecently: "A written first step and visual checklist led to stronger engagement after lunch.",
        preferredCommunicationStyle: "Written choices and private check-ins.",
        helpSigns: "Shares a draft comment or says, 'I don't know where to start.'",
        confusedSigns: "Scrolls document, changes font, opens unrelated tabs.",
        overwhelmedSigns: "Hood up, head down, says task is pointless.",
        bestPrompts: "Offer a concrete first step and connect to creative choice.",
        peerNotes: "Does best in writing partnerships with clear feedback roles.",
        speechLanguageNotes: "Written expression is a strength and self-advocacy tool.",
        conversationStarters: "Ask about character, playlist, or favorite line.",
        whatNotToDo: "Avoid public pressure to share unfinished work.",
        arrival: "Settles with notebook or laptop open.",
        transitionSupport: "Post-lunch reset and first step.",
        materialsOrganization: "Digital folder naming needs periodic check.",
        breaksNeeded: "Quiet break after lunch supports regulation.",
        homeworkSupport: "Milestone planner for longer writing.",
        seating: "Quiet side, permission for headphones during drafting.",
        reminders: "Milestone tracker every Friday.",
        attendanceNotes: "Consistent attendance.",
        supportChecklist: ["First-step card", "Milestone planner", "Headphones option"],
        efBestSupports: "Written first step, visual checklist, project milestones.",
        efCurrentGoal: "Initiate writing with first-step card within five minutes.",
        efNextStrategy: "Start class with a two-minute micro-draft.",
        sensorySensitivities: "Noise after lunch and overlapping group conversations.",
        sensorySeeking: "Music can support drafting when permitted.",
        helpfulTools: "Headphones, quiet drafting station, visual checklist.",
        calmingStrategies: "Quiet space, music, micro-draft prompt.",
        regulationSigns: "Opens document, writes first sentence, uses headphones.",
        escalationSigns: "Head down, avoidant comments, refusal to open assignment.",
        recoveryStrategies: "Reduce demand, offer first sentence choice, return with private check-in.",
        environmentalTriggers: "Post-lunch noise and broad open-ended tasks.",
        breakOptions: "Quiet space, water walk, two-minute playlist reset.",
      },
      createdAt: "2026-06-01T08:27:00.000Z",
      updatedAt: "2026-07-08T15:55:00.000Z",
    },
    {
      id: "stu-priya-shah",
      firstName: "Priya",
      lastName: "Shah",
      grade: "9",
      email: "priya.shah@student.stanbridge.example",
      photoUrl: "",
      supportSummary: "Strong visual artist navigating high school workload; benefits from planning frames and supportive self-monitoring.",
      supportNeeds: ["Transition Planning", "Executive Functioning", "Anxiety"],
      strengths: ["Visual design", "Persistence", "Detail"],
      motivators: ["Portfolio work", "Choice projects", "One-to-one critique"],
      sensoryNeeds: ["Quiet studio option", "Predictable critique format"],
      triggers: ["Multiple due dates", "Public critique without preview"],
      communicationStyle: "Reflective and concise; more comfortable with prepared comments.",
      accommodations: ["Weekly workload map", "Critique preview", "Private progress check"],
      currentGoals: ["Use weekly workload map", "Submit staged project milestones"],
      parentContacts: [{ name: "Anika Shah", email: "anika.shah@example.com", phone: "(415) 555-0111", relationship: "Mother" }],
      emergencyContacts: [{ name: "Dev Shah", phone: "(415) 555-0139", relationship: "Father" }],
      profile: {
        interests: "Digital illustration, architecture, fashion design, playlists.",
        preferredActivities: "Portfolio projects, visual planning, private critique.",
        confidenceBuilders: "Notice process choices and completion milestones.",
        successfulMoments: "Priya submitted two project milestones after using the workload map.",
        whatWorkedRecently: "Friday planning conference helped her prioritize assignments.",
        preferredCommunicationStyle: "Prepared written comments and private conferences.",
        helpSigns: "Quietly asks for deadline clarification.",
        confusedSigns: "Reworks details before core task is complete.",
        overwhelmedSigns: "Freezes on planning page, avoids email, tearful after critique.",
        bestPrompts: "Ask which deadline is first and what 'done enough' looks like.",
        peerNotes: "Thrives with kind critique protocol.",
        speechLanguageNotes: "Prepared sentence frames support critique participation.",
        conversationStarters: "Design inspiration, color palette, portfolio goal.",
        whatNotToDo: "Avoid surprise public critique.",
        arrival: "Checks weekly map when prompted.",
        transitionSupport: "High school workload preview on Mondays.",
        materialsOrganization: "Digital files need folder routine.",
        breaksNeeded: "Short reset before critique.",
        homeworkSupport: "Parent-visible workload summary.",
        seating: "Quiet studio edge.",
        reminders: "Digital folder backup and deadline map.",
        attendanceNotes: "Consistent attendance.",
        supportChecklist: ["Workload map", "Critique preview", "Milestone dates"],
        efBestSupports: "Weekly map, staged milestones, 'done enough' criteria.",
        efCurrentGoal: "Submit staged project milestones.",
        efNextStrategy: "Add color-coded urgency labels to workload map.",
        sensorySensitivities: "Public critique and bright studio noise.",
        sensorySeeking: "Detail work can be regulating but may lead to over-focus.",
        helpfulTools: "Timer, quiet studio corner, critique script.",
        calmingStrategies: "Private preview, five-minute reset, priority sort.",
        regulationSigns: "Names first deadline and starts broad draft.",
        escalationSigns: "Perfectionistic loop, tears, avoidance.",
        recoveryStrategies: "Define minimum viable next step and private check-in.",
        environmentalTriggers: "Multiple deadlines and surprise critique.",
        breakOptions: "Quiet studio reset or short walk.",
      },
      createdAt: "2026-06-01T08:28:00.000Z",
      updatedAt: "2026-07-07T18:05:00.000Z",
    },
    {
      id: "stu-ethan-garcia",
      firstName: "Ethan",
      lastName: "Garcia",
      grade: "10",
      email: "ethan.garcia@student.stanbridge.example",
      photoUrl: "",
      supportSummary: "Hands-on problem solver who engages strongly in applied learning and needs support with written reflection and follow-through.",
      supportNeeds: ["Executive Functioning", "Writing Support", "Transition Planning"],
      strengths: ["Mechanical reasoning", "Persistence with tools", "Practical problem solving"],
      motivators: ["Maker projects", "Automotive examples", "Choice of tool role"],
      sensoryNeeds: ["Hands-on movement", "Clear lab expectations"],
      triggers: ["Long written reflections", "Unclear cleanup roles"],
      communicationStyle: "Direct and practical; responds best to concrete purpose.",
      accommodations: ["Checklist for lab cleanup", "Reflection sentence frames", "Applied examples"],
      currentGoals: ["Complete reflection using frame", "Independently check off cleanup role"],
      parentContacts: [{ name: "Carla Garcia", email: "carla.garcia@example.com", phone: "(415) 555-0112", relationship: "Mother" }],
      emergencyContacts: [{ name: "Miguel Garcia", phone: "(415) 555-0140", relationship: "Father" }],
      profile: {
        interests: "Maker lab, engines, woodworking, practical physics.",
        preferredActivities: "Applied projects, tool roles, demonstration before writing.",
        confidenceBuilders: "Name the concrete problem he solved.",
        successfulMoments: "Ethan completed the lab cleanup checklist and wrote a concise reflection.",
        whatWorkedRecently: "Sentence frames connected the build to physics vocabulary.",
        preferredCommunicationStyle: "Concrete purpose and direct feedback.",
        helpSigns: "Waits by materials or asks, 'What are we actually doing?'",
        confusedSigns: "Starts tool work before reading directions.",
        overwhelmedSigns: "Pushes written task away or disengages.",
        bestPrompts: "Connect task to real-world use and show checklist.",
        peerNotes: "Useful leader when safety role is explicit.",
        speechLanguageNotes: "Vocabulary bridge supports written reflection.",
        conversationStarters: "Tool choice, repair problem, practical design.",
        whatNotToDo: "Avoid abstract rationale without concrete example.",
        arrival: "Ready for hands-on work; needs planner check.",
        transitionSupport: "Explicit cleanup role and timing.",
        materialsOrganization: "Lab checklist and folder audit.",
        breaksNeeded: "Hands-on engagement is regulating.",
        homeworkSupport: "Reflection frame sent home.",
        seating: "Near lab demonstration, low-distraction writing station.",
        reminders: "Cleanup checklist and reflection frame.",
        attendanceNotes: "Consistent attendance.",
        supportChecklist: ["Cleanup role", "Reflection frame", "Planner check"],
        efBestSupports: "Checklist, visible due date, practical purpose.",
        efCurrentGoal: "Complete written reflections with frame.",
        efNextStrategy: "Use voice memo before writing reflection.",
        sensorySensitivities: "Frustration with long seated writing.",
        sensorySeeking: "Tool work, carrying supplies, standing workbench.",
        helpfulTools: "Workbench, cleanup checklist, voice memo.",
        calmingStrategies: "Hands-on reset and concrete next step.",
        regulationSigns: "Checks role, starts build, writes bullet.",
        escalationSigns: "Pushes paper away and avoids reflection.",
        recoveryStrategies: "Oral explanation first, then sentence frame.",
        environmentalTriggers: "Long abstract written tasks.",
        breakOptions: "Supply run or workbench reset.",
      },
      createdAt: "2026-06-01T08:29:00.000Z",
      updatedAt: "2026-07-08T11:35:00.000Z",
    },
    {
      id: "stu-sofia-nguyen",
      firstName: "Sofia",
      lastName: "Nguyen",
      grade: "11",
      email: "sofia.nguyen@student.stanbridge.example",
      photoUrl: "",
      supportSummary: "Insightful, justice-oriented student who benefits from transparent expectations, debate structure, and workload planning.",
      supportNeeds: ["Executive Functioning", "Communication", "Anxiety"],
      strengths: ["Critical thinking", "Advocacy", "Research"],
      motivators: ["Debate", "Social impact topics", "Independent research"],
      sensoryNeeds: ["Quiet planning time", "Predictable discussion norms"],
      triggers: ["Ambiguous grading", "Unstructured debate", "Compressed deadlines"],
      communicationStyle: "Strong verbal reasoning; benefits from clear discussion protocols.",
      accommodations: ["Rubric preview", "Discussion role", "Deadline map"],
      currentGoals: ["Use rubric to plan work", "Pause and use discussion protocol when disagreement rises"],
      parentContacts: [{ name: "Mai Nguyen", email: "mai.nguyen@example.com", phone: "(415) 555-0113", relationship: "Mother" }],
      emergencyContacts: [{ name: "Bao Nguyen", phone: "(415) 555-0141", relationship: "Father" }],
      profile: {
        interests: "Civic issues, debate, research, documentary film.",
        preferredActivities: "Structured discussion, independent inquiry, annotated sources.",
        confidenceBuilders: "Invite expertise with defined boundaries.",
        successfulMoments: "Sofia used the discussion protocol to disagree respectfully and cite evidence.",
        whatWorkedRecently: "Rubric preview reduced anxiety before research work time.",
        preferredCommunicationStyle: "Transparent rationale and collaborative planning.",
        helpSigns: "Challenges wording or asks detailed policy questions.",
        confusedSigns: "Focuses on fairness of task rather than start.",
        overwhelmedSigns: "Intense debate tone, shuts laptop, avoids submission portal.",
        bestPrompts: "Validate concern, name the standard, and choose first evidence task.",
        peerNotes: "Can elevate groups when role and protocol are clear.",
        speechLanguageNotes: "Discussion protocols support pragmatic flexibility.",
        conversationStarters: "Current events, research question, documentary.",
        whatNotToDo: "Avoid dismissing concerns as argumentativeness.",
        arrival: "Prepared when deadline map is current.",
        transitionSupport: "Preview grading expectations.",
        materialsOrganization: "Digital source folders need checks.",
        breaksNeeded: "Quiet planning after intense discussion.",
        homeworkSupport: "Deadline map and rubric check.",
        seating: "Near discussion anchor, not center of every debate.",
        reminders: "Submission portal and source folder.",
        attendanceNotes: "Consistent attendance.",
        supportChecklist: ["Rubric", "Deadline map", "Discussion role"],
        efBestSupports: "Rubric preview, deadline map, source folder routine.",
        efCurrentGoal: "Use rubric to plan research milestones.",
        efNextStrategy: "Add self-monitoring checklist before submission.",
        sensorySensitivities: "High-intensity debate and deadline compression.",
        sensorySeeking: "Deep research focus.",
        helpfulTools: "Rubric, quiet planning block, discussion role card.",
        calmingStrategies: "Private planning conference and evidence sort.",
        regulationSigns: "Cites evidence and returns to rubric.",
        escalationSigns: "Intense tone, laptop closed, refusal language.",
        recoveryStrategies: "Name shared goal and offer first evidence step.",
        environmentalTriggers: "Ambiguous grading and unstructured debate.",
        breakOptions: "Quiet research station or planning walk.",
      },
      createdAt: "2026-06-01T08:30:00.000Z",
      updatedAt: "2026-07-07T20:30:00.000Z",
    },
    {
      id: "stu-caleb-morgan",
      firstName: "Caleb",
      lastName: "Morgan",
      grade: "12",
      email: "caleb.morgan@student.stanbridge.example",
      photoUrl: "",
      supportSummary: "Senior preparing for transition; benefits from explicit planning for deadlines, advocacy scripts, and postsecondary routines.",
      supportNeeds: ["Transition Planning", "Executive Functioning", "Self-Advocacy"],
      strengths: ["Technology", "Mentoring younger students", "Calm problem solving"],
      motivators: ["Internship tasks", "Tech support role", "Real-world deadlines"],
      sensoryNeeds: ["Quiet testing space", "Predictable schedule"],
      triggers: ["Multiple graduation requirements", "Open-ended independent work"],
      communicationStyle: "Mature and calm; may underreport stress until deadlines stack.",
      accommodations: ["Transition checklist", "Weekly deadline audit", "Advocacy script practice"],
      currentGoals: ["Use transition checklist weekly", "Email teachers with support request before deadline"],
      parentContacts: [{ name: "Dana Morgan", email: "dana.morgan@example.com", phone: "(415) 555-0114", relationship: "Parent" }],
      emergencyContacts: [{ name: "Lee Morgan", phone: "(415) 555-0142", relationship: "Parent" }],
      profile: {
        interests: "Tech support, cybersecurity, mentoring, practical life skills.",
        preferredActivities: "Internship-style tasks, troubleshooting, checklists.",
        confidenceBuilders: "Connect work to postsecondary independence.",
        successfulMoments: "Caleb emailed a teacher proactively about a deadline extension plan.",
        whatWorkedRecently: "Weekly deadline audit kept transition tasks visible.",
        preferredCommunicationStyle: "Adult-to-adult tone and direct planning.",
        helpSigns: "Says 'I'm good' but tasks remain incomplete.",
        confusedSigns: "Skips steps in transition checklist.",
        overwhelmedSigns: "Avoids email and delays independent work.",
        bestPrompts: "Ask him to identify deadline, barrier, and next email.",
        peerNotes: "Positive mentor with tech support role.",
        speechLanguageNotes: "Advocacy scripts support postsecondary communication.",
        conversationStarters: "Tech troubleshooting, internship, graduation plan.",
        whatNotToDo: "Avoid assuming calm presentation means workload is managed.",
        arrival: "Checks transition board on Mondays.",
        transitionSupport: "Weekly deadline audit.",
        materialsOrganization: "Digital checklist and calendar invite.",
        breaksNeeded: "Quiet planning block before independent work.",
        homeworkSupport: "Calendar and email draft routine.",
        seating: "Independent work station.",
        reminders: "Transition checklist and email draft.",
        attendanceNotes: "Consistent attendance.",
        supportChecklist: ["Deadline audit", "Transition checklist", "Advocacy script"],
        efBestSupports: "Calendar, checklist, email script, weekly audit.",
        efCurrentGoal: "Initiate support request email before due date.",
        efNextStrategy: "Use template with deadline, barrier, plan.",
        sensorySensitivities: "Testing noise and deadline pile-up.",
        sensorySeeking: "Tech repair tasks can regulate.",
        helpfulTools: "Calendar reminders, quiet testing, email templates.",
        calmingStrategies: "Break requirements into next action list.",
        regulationSigns: "Drafts email and updates calendar.",
        escalationSigns: "Task avoidance masked by calm reassurance.",
        recoveryStrategies: "Private audit and one email action.",
        environmentalTriggers: "Multiple transition tasks due together.",
        breakOptions: "Tech support task or quiet planning block.",
      },
      createdAt: "2026-06-01T08:31:00.000Z",
      updatedAt: "2026-07-08T10:15:00.000Z",
    },
  ];

  const notes = [
    {
      id: "note-001",
      studentId: "stu-jordan-lee",
      authorId: teacherA.id,
      authorName: teacherA.name,
      authorEmail: teacherA.email,
      type: "Spark",
      sourceTab: "Spark Profile",
      text: "Jordan wrote a compelling opening scene when the prompt allowed a character voice. Creative writing is a strong entry point.",
      category: "Successful moment",
      tags: ["creative writing", "strong focus", "confidence"],
      classSetting: "English",
      visibility: "include in parent report",
      includeInWeeklyReport: true,
      createdAt: "2026-07-08T15:55:00.000Z",
      updatedAt: "2026-07-08T15:55:00.000Z",
    },
    {
      id: "note-002",
      studentId: "stu-jordan-lee",
      authorId: teacherB.id,
      authorName: teacherB.name,
      authorEmail: teacherB.email,
      type: "Observation",
      sourceTab: "Engagement Log",
      text: "After lunch noise, Jordan needed a quiet space and then returned with the visual checklist. Recovered and completed the first paragraph.",
      category: "Regulation",
      tags: ["sensory overload", "visual checklist helped", "break helped", "recovered"],
      classSetting: "Humanities",
      visibility: "include in parent report",
      includeInWeeklyReport: true,
      createdAt: "2026-07-08T13:40:00.000Z",
      updatedAt: "2026-07-08T13:40:00.000Z",
    },
    {
      id: "note-003",
      studentId: "stu-oliver-kim",
      authorId: teacherB.id,
      authorName: teacherB.name,
      authorEmail: teacherB.email,
      type: "Communication",
      sourceTab: "Communication",
      text: "Role cards helped Oliver participate in robotics without correcting peers as frequently. He completed the data lead role.",
      category: "Peer communication",
      tags: ["group work challenge", "structured peer roles", "peer success"],
      classSetting: "Robotics",
      visibility: "internal only",
      includeInWeeklyReport: false,
      createdAt: "2026-07-08T17:05:00.000Z",
      updatedAt: "2026-07-08T17:05:00.000Z",
    },
    {
      id: "note-004",
      studentId: "stu-nia-patel",
      authorId: teacherA.id,
      authorName: teacherA.name,
      authorEmail: teacherA.email,
      type: "Concern",
      sourceTab: "Daily Needs",
      text: "Nia froze during an unmodeled writing task with a substitute. She recovered after a private check-in and a two-column planning frame.",
      category: "Writing initiation",
      tags: ["follow-up needed", "writing support", "anxiety", "visual checklist helped"],
      classSetting: "Writing",
      visibility: "internal only",
      includeInWeeklyReport: false,
      createdAt: "2026-07-08T16:40:00.000Z",
      updatedAt: "2026-07-08T16:40:00.000Z",
    },
    {
      id: "note-005",
      studentId: "stu-mateo-chen",
      authorId: teacherA.id,
      authorName: teacherA.name,
      authorEmail: teacherA.email,
      type: "Executive Functioning",
      sourceTab: "Executive Functioning",
      text: "Mateo used the station checklist to complete three tasks with only one reminder.",
      category: "Checklist use",
      tags: ["visual checklist helped", "completed assignment", "independent work"],
      classSetting: "Math centers",
      visibility: "include in parent report",
      includeInWeeklyReport: true,
      createdAt: "2026-07-08T13:50:00.000Z",
      updatedAt: "2026-07-08T13:50:00.000Z",
    },
    {
      id: "note-006",
      studentId: "stu-ava-brooks",
      authorId: teacherB.id,
      authorName: teacherB.name,
      authorEmail: teacherB.email,
      type: "Sensory/Regulation",
      sourceTab: "Sensory & Regulation",
      text: "Headphones and line-helper role supported Ava during the hallway transition.",
      category: "Transition",
      tags: ["used headphones", "transition support", "positive participation"],
      classSetting: "Arrival",
      visibility: "include in parent report",
      includeInWeeklyReport: true,
      createdAt: "2026-07-08T15:20:00.000Z",
      updatedAt: "2026-07-08T15:20:00.000Z",
    },
    {
      id: "note-007",
      studentId: "stu-maya-thompson",
      authorId: teacherA.id,
      authorName: teacherA.name,
      authorEmail: teacherA.email,
      type: "Daily Needs",
      sourceTab: "Daily Needs",
      text: "Locker checklist worked well today. Maya arrived to science with all materials.",
      category: "Materials",
      tags: ["transition planning", "completed independently", "confidence"],
      classSetting: "Science",
      visibility: "include in parent report",
      includeInWeeklyReport: true,
      createdAt: "2026-07-08T12:10:00.000Z",
      updatedAt: "2026-07-08T12:10:00.000Z",
    },
    {
      id: "note-008",
      studentId: "stu-caleb-morgan",
      authorId: admin.id,
      authorName: admin.name,
      authorEmail: admin.email,
      type: "Transition Planning",
      sourceTab: "Engagement Log",
      text: "Caleb drafted a clear support request email before the transition portfolio deadline.",
      category: "Self-advocacy",
      tags: ["transition planning", "asked for help", "independent work"],
      classSetting: "Advisory",
      visibility: "include in parent report",
      includeInWeeklyReport: true,
      createdAt: "2026-07-08T10:15:00.000Z",
      updatedAt: "2026-07-08T10:15:00.000Z",
    },
    {
      id: "note-009",
      studentId: "stu-sofia-nguyen",
      authorId: teacherB.id,
      authorName: teacherB.name,
      authorEmail: teacherB.email,
      type: "Communication",
      sourceTab: "Communication",
      text: "Sofia used the discussion protocol to disagree respectfully and return to evidence.",
      category: "Social learning",
      tags: ["peer success", "communication", "strong participation"],
      classSetting: "History",
      visibility: "include in parent report",
      includeInWeeklyReport: true,
      createdAt: "2026-07-07T20:30:00.000Z",
      updatedAt: "2026-07-07T20:30:00.000Z",
    },
    {
      id: "note-010",
      studentId: "stu-ethan-garcia",
      authorId: teacherA.id,
      authorName: teacherA.name,
      authorEmail: teacherA.email,
      type: "Engagement",
      sourceTab: "Engagement Log",
      text: "Ethan completed the lab cleanup role and used a reflection frame to connect the build to physics vocabulary.",
      category: "Applied learning",
      tags: ["completed assignment", "writing support", "independent work"],
      classSetting: "Physics lab",
      visibility: "include in parent report",
      includeInWeeklyReport: true,
      createdAt: "2026-07-08T11:35:00.000Z",
      updatedAt: "2026-07-08T11:35:00.000Z",
    },
    {
      id: "note-011",
      studentId: "stu-priya-shah",
      authorId: admin.id,
      authorName: admin.name,
      authorEmail: admin.email,
      type: "Executive Functioning",
      sourceTab: "Executive Functioning",
      text: "Weekly workload map helped Priya select the first two project milestones.",
      category: "Planning",
      tags: ["planning", "visual checklist helped", "anxiety support"],
      classSetting: "Advisory",
      visibility: "include in parent report",
      includeInWeeklyReport: true,
      createdAt: "2026-07-07T18:05:00.000Z",
      updatedAt: "2026-07-07T18:05:00.000Z",
    },
    {
      id: "note-012",
      studentId: "stu-zoe-alvarez",
      authorId: teacherA.id,
      authorName: teacherA.name,
      authorEmail: teacherA.email,
      type: "Spark",
      sourceTab: "Spark Profile",
      text: "Zoe explained a science diagram beautifully using a sentence starter and her own labels.",
      category: "Confidence builder",
      tags: ["visual thinking", "communication", "science strength"],
      classSetting: "Science",
      visibility: "include in parent report",
      includeInWeeklyReport: true,
      createdAt: "2026-07-08T14:30:00.000Z",
      updatedAt: "2026-07-08T14:30:00.000Z",
    },
  ];

  const engagementLogs = [
    {
      id: "eng-001",
      studentId: "stu-jordan-lee",
      authorId: teacherB.id,
      authorName: teacherB.name,
      authorEmail: teacherB.email,
      date: "2026-07-08T13:35:00.000Z",
      classSetting: "Humanities",
      engagementLevel: "Recovered",
      academicParticipation: "Completed the first paragraph after a quiet reset.",
      socialParticipation: "Chose independent drafting after group warm-up.",
      independenceLevel: "Completed with some support",
      supportNeeded: "Written first step, quiet space, visual checklist.",
      whatHappened: "Post-lunch noise appeared to make starting the assignment difficult.",
      whatHelped: "Quiet space and a clear first written step.",
      whatDidNotHelp: "Verbal reminders before the first step was visible.",
      followUpNeeded: false,
      tags: ["sensory overload", "visual checklist helped", "break helped", "recovered"],
      includeInWeeklyReport: true,
      createdAt: "2026-07-08T13:45:00.000Z",
    },
    {
      id: "eng-002",
      studentId: "stu-oliver-kim",
      authorId: teacherB.id,
      authorName: teacherB.name,
      authorEmail: teacherB.email,
      date: "2026-07-08T16:45:00.000Z",
      classSetting: "Robotics",
      engagementLevel: "Medium",
      academicParticipation: "Completed data lead role accurately.",
      socialParticipation: "Needed one reminder to use role language with peers.",
      independenceLevel: "Mostly independent",
      supportNeeded: "Role card and noise plan.",
      whatHappened: "Group work became noisy after lunch.",
      whatHelped: "Structured peer roles.",
      whatDidNotHelp: "Open-ended group negotiation.",
      followUpNeeded: false,
      tags: ["group work challenge", "peer success", "structured peer roles"],
      includeInWeeklyReport: false,
      createdAt: "2026-07-08T17:05:00.000Z",
    },
    {
      id: "eng-003",
      studentId: "stu-nia-patel",
      authorId: teacherA.id,
      authorName: teacherA.name,
      authorEmail: teacherA.email,
      date: "2026-07-08T16:10:00.000Z",
      classSetting: "Writing",
      engagementLevel: "Low",
      academicParticipation: "Started after private check-in and planning frame.",
      socialParticipation: "Worked independently.",
      independenceLevel: "Needed frequent prompting",
      supportNeeded: "Model text and planning frame.",
      whatHappened: "Writing task was introduced by a substitute without the usual model.",
      whatHelped: "Private check-in and two-column frame.",
      whatDidNotHelp: "Whole-class repeated verbal directions.",
      followUpNeeded: true,
      tags: ["anxiety", "task avoidance", "visual checklist helped", "follow-up needed"],
      includeInWeeklyReport: false,
      createdAt: "2026-07-08T16:40:00.000Z",
    },
    {
      id: "eng-004",
      studentId: "stu-mateo-chen",
      authorId: teacherA.id,
      authorName: teacherA.name,
      authorEmail: teacherA.email,
      date: "2026-07-08T13:20:00.000Z",
      classSetting: "Math centers",
      engagementLevel: "High",
      academicParticipation: "Completed three stations with one reminder.",
      socialParticipation: "Shared materials appropriately after visual prompt.",
      independenceLevel: "Mostly independent",
      supportNeeded: "Station checklist.",
      whatHappened: "Hands-on stations matched Mateo's strengths.",
      whatHelped: "Visual checklist and movement between stations.",
      whatDidNotHelp: "Long carpet review before centers.",
      followUpNeeded: false,
      tags: ["strong focus", "completed assignment", "visual checklist helped"],
      includeInWeeklyReport: true,
      createdAt: "2026-07-08T13:50:00.000Z",
    },
    {
      id: "eng-005",
      studentId: "stu-ava-brooks",
      authorId: teacherB.id,
      authorName: teacherB.name,
      authorEmail: teacherB.email,
      date: "2026-07-08T15:00:00.000Z",
      classSetting: "Arrival",
      engagementLevel: "Medium",
      academicParticipation: "Completed picture-sort task.",
      socialParticipation: "Greeted peer with gesture.",
      independenceLevel: "Completed with some support",
      supportNeeded: "Picture schedule and headphones.",
      whatHappened: "Hallway was loud during arrival.",
      whatHelped: "Line-helper role and headphones.",
      whatDidNotHelp: "Verbal countdown in noisy space.",
      followUpNeeded: false,
      tags: ["used headphones", "transition support", "positive peer interaction"],
      includeInWeeklyReport: true,
      createdAt: "2026-07-08T15:20:00.000Z",
    },
  ];

  const executiveFunctionLogs = [
    {
      id: "ef-001",
      studentId: "stu-jordan-lee",
      authorId: teacherA.id,
      authorName: teacherA.name,
      authorEmail: teacherA.email,
      date: "2026-07-08T15:30:00.000Z",
      taskInitiation: 4,
      planning: 3,
      organization: 3,
      timeManagement: 3,
      workingMemory: 4,
      flexibility: 3,
      selfMonitoring: 3,
      homeworkCompletion: 3,
      assignmentTracking: 3,
      projectBreakdown: 3,
      independenceLevel: 4,
      notes: "Initiated writing once first step was visible. Milestone planning still needs support.",
      createdAt: "2026-07-08T15:50:00.000Z",
    },
    {
      id: "ef-002",
      studentId: "stu-mateo-chen",
      authorId: teacherA.id,
      authorName: teacherA.name,
      authorEmail: teacherA.email,
      date: "2026-07-08T13:30:00.000Z",
      taskInitiation: 4,
      planning: 3,
      organization: 3,
      timeManagement: 3,
      workingMemory: 3,
      flexibility: 3,
      selfMonitoring: 3,
      homeworkCompletion: 3,
      assignmentTracking: 3,
      projectBreakdown: 2,
      independenceLevel: 4,
      notes: "Checklist supported independent station completion.",
      createdAt: "2026-07-08T13:50:00.000Z",
    },
    {
      id: "ef-003",
      studentId: "stu-nia-patel",
      authorId: teacherA.id,
      authorName: teacherA.name,
      authorEmail: teacherA.email,
      date: "2026-07-08T16:20:00.000Z",
      taskInitiation: 2,
      planning: 3,
      organization: 4,
      timeManagement: 3,
      workingMemory: 3,
      flexibility: 2,
      selfMonitoring: 3,
      homeworkCompletion: 4,
      assignmentTracking: 4,
      projectBreakdown: 3,
      independenceLevel: 2,
      notes: "Needed frequent prompting during substitute-led writing task; planning frame improved initiation.",
      createdAt: "2026-07-08T16:40:00.000Z",
    },
  ];

  const reports = [
    {
      id: "report-001",
      studentId: "stu-jordan-lee",
      createdBy: teacherA.id,
      createdByName: teacherA.name,
      dateRangeStart: "2026-07-01",
      dateRangeEnd: "2026-07-07",
      title: "Weekly Spark Report: July 1-7",
      status: "Ready to Send",
      content:
        "Positive Highlights\nJordan showed strong creative voice in writing and used character development as a meaningful entry point.\n\nAcademic Engagement\nJordan engaged most strongly when the first step was written clearly and the assignment connected to creative choice.\n\nStrategies That Helped\nA visual checklist, quiet drafting space, and short first-step prompt supported successful work initiation.\n\nGoals for Next Week\nContinue using the milestone planner for longer writing assignments.",
      includedNoteIds: ["note-001", "note-002"],
      createdAt: "2026-07-07T22:00:00.000Z",
      updatedAt: "2026-07-07T22:15:00.000Z",
      sentAt: "",
    },
  ];

  const emergencyParentNotes = [
    {
      id: "emg-001",
      studentId: "stu-nia-patel",
      createdBy: teacherA.id,
      createdByName: teacherA.name,
      reason: "Extended anxiety response during writing transition",
      whatHappened: "Nia became tearful and could not start the task after an unexpected substitute-led writing prompt.",
      studentStatusNow: "Regulated after private check-in and planning frame; returned to classwork.",
      actionTaken: "Teacher check-in, quiet reset, planning support, admin notified.",
      followUpNeeded: "Team should review substitute transition plan and writing model availability.",
      parentContactMethod: "Phone call",
      contacted: false,
      resolved: false,
      createdAt: "2026-07-08T16:45:00.000Z",
      resolvedAt: "",
    },
  ];

  window.StanbridgeDemo = {
    users: [teacherA, teacherB, admin],
    students,
    notes,
    engagementLogs,
    executiveFunctionLogs,
    reports,
    emergencyParentNotes,
    activity: [],
    settings: {
      allowTeachersEditStudentInfo: true,
    },
  };
})();
